version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: smart_quiz_api
    volumes:
      - ./smart_quiz_api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    container_name: smart_quiz_frontend
    volumes:
      - ./smart_quiz_frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
