services:
  - type: web
    name: smart-quiz-master-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    rootDir: backend
